name: Run SAST and SCA jobs - Part 1

# Run when a push/pull request is made to the master branch
on:
    push:
        branches: [ "master" ]
    pull_request: 
        branches: [ "master" ]

jobs:
  # Post a message to the ITAS Discord channel reporting that the pipeline has started.
  Discord-Begin:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_TEST }}
          username: ${{github.repository}}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Security Pipeline jobs are starting..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
          embed-author-icon-url: https://gravatar.com/avatar/${{ github.triggering_actor }}?s=200
          embed-color: 629
          embed-footer-text: "Preparing to run SNYK and SEMGREP scans..."
              
  # Runs a semgrep SAST scan and uploads a SARIF file report.
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    outputs:
        # Sets artifact url to a variable for discord notifactions to use
        semgrep-url: ${{ steps.upload-semgrep.outputs.artifact-url }}
    container:
        image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Clone app code
        uses: actions/checkout@v4
      - name: Run semgrep scan
        run: semgrep ci --sarif-output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Upload report
        uses: actions/upload-artifact@v4
        id: upload-semgrep
        with:
          name: semgrep.sarif
          path: semgrep.sarif

  # Run a snyk SCA scan and uploads a sarif file report.
  snyk:
    name: snyk
    runs-on: ubuntu-latest
    outputs:
        # Sets artifact url to a variable for discord notifactions to use
        artifact-url: ${{ steps.upload-snyk.outputs.artifact-url }}
    steps:
      - name: Clone app code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker image
        run: docker pull kevyy/assignment01:latest
      - name: Run snyk to check docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: kevyy/assignment01:latest
          args: --file=Dockerfile
      - name: Upload report
        uses: actions/upload-artifact@v4
        id: upload-snyk
        with:
          name: snyk-sca.sarif
          path: snyk.sarif
          
  # Post a message to the ITAS Discord channel reporting that the Snyk scan has completed.     
  Discord-Snyk-Completed:
    runs-on: ubuntu-latest
    needs: [snyk]
    steps:
        - name: Discord Notification Synk Scan Complete
          uses: tsickert/discord-webhook@v5.3.0
          with:
            webhook-url: ${{ secrets.DISCORD_WEBHOOK_TEST }}
            username: ${{github.repository}}
            avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
            embed-title: "Snyk Scan Completed"
            embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            # Uses the output from the snyk scan for artifact download.
            embed-description: "Uploaded Report: [SNYK Sarif Report](${{ needs.snyk.outputs.artifact-url }})"
            embed-author-name: "${{ github.triggering_actor }}"
            embed-author-icon-url: https://gravatar.com/avatar/${{ github.triggering_actor }}?s=200
            embed-color: 629
            embed-footer-text: "Snyk Scan Completed. Cick above link to download report."
            
  # Post a message to the ITAS Discord channel reporting that the semgrep scan has completed.           
  Discord-Semgrep-Completed:
      runs-on: ubuntu-latest
      needs: [semgrep]
      steps:
          - name: Discord Notification Semgrep Scan Complete
            uses: tsickert/discord-webhook@v5.3.0
            with:
              webhook-url: ${{ secrets.DISCORD_WEBHOOK_TEST }}
              username: ${{github.repository}}
              avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
              embed-title: "Semgrep Scan Completed"
              embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              # Uses the output from the semgrep scan for artifact download.
              embed-description: "Uploaded Report: [Semgrep Sarif Report](${{ needs.semgrep.outputs.semgrep-url }})"
              embed-author-name: "${{ github.triggering_actor }}"
              embed-author-icon-url: https://gravatar.com/avatar/${{ github.triggering_actor }}?s=200
              embed-color: 629
              embed-footer-text: "Semgrep Scan Completed."

  # Post a message to the ITAS Discord Channel when Pipeline finishes.
  Discord-Finish:
    runs-on: ubuntu-latest
    needs: [semgrep, snyk]
    steps:
      - name: Discord Notification End
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_TEST }}
          username: ${{github.repository}}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Security Pipeline jobs Completed."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
          embed-author-icon-url: https://gravatar.com/avatar/${{ github.triggering_actor }}?s=200
          embed-color: 629
          embed-footer-text: "SNYK and SEMGREP security scans both successfully completed."
