name: Run SAST and SCA jobs - Part 1

# Run when a push/pull request is made to the master branch
on:
    push:
        branches: [ "master" ]
    pull_request: 
        branches: [ "master" ]

jobs:
  # Post a message to the ITAS Discord channel with pipeline updates.
  Discord-Begin:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Security Pipeline jobs are starting..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
          embed-author-icon-url: https://gravatar.com/avatar/${{ github.triggering_actor }}?s=200
          embed-color: 629
          embed-footer-text: "Preparing to run security scans..."
              
  # Runs a semgrep SAST scan
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
        image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Clone app code
        uses: actions/checkout@v4
      - name: Run semgrep scan
        run: semgrep ci --sarif-output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep.sarif
          path: semgrep.sarif

  # Run a snyk SCA scan
  snyk:
    name: snyk
    runs-on: ubuntu-latest
    steps:
      - name: Clone app code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker image
        run: docker pull kevyy/assignment01:latest
      - name: Run snyk to check docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: kevyy/assignment01:latest
          args: --file=Dockerfile
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sca.sarif
          path: snyk.sarif
          
  Discord-Snyk-Completed:
    runs-on: ubuntu-latest
    needs: [snyk]
    steps:
        - name: Download snyk.sarif artifact
          uses: actions/download-artifact@v2
          with:
            name: snyk.sarif
        - name: Discord Notification Synk Scan Complete
        - uses: tsickert/discord-webhook@v5.3.0
          with:
            webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
            username: ${{github.repository}}
            avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
            embed-title: "Snyk Scan Completed"
            embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            embed-description: "Uploaded File:"
            embed-author-name: "${{ github.triggering_actor }}"
            embed-author-icon-url: https://gravatar.com/avatar/${{ github.triggering_actor }}?s=200
            embed-color: 629
            embed-footer-text: "Snyk Scan Completed."
            filename: snyk.sarif

  # Post a message to the ITAS Discord Channel when Pipeline finishes.
  Discord-Finish:
    runs-on: ubuntu-latest
    needs: [semgrep, snyk]
    steps:
      - name: Discord Notification End
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
          embed-title: "Security Pipeline jobs Completed."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
          embed-author-icon-url: https://gravatar.com/avatar/${{ github.triggering_actor }}?s=200
          embed-color: 629
          embed-footer-text: "Security scans completed."
